/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 * Programa : 001HelloWorld
 * Propósito: - Utilizar el protocolo SWV (Serial Wired Communication) para
 *              imprimir mensajes por pantalla.
 *            - Para esto se utiliza el pin SWO (Serial Wired Output) que
 *              comunica el circuito de depuración ST-Link con el procesador.
 *            - La interface de comunicación es SWD (Serial Wired Debug), a
 *              two-wired protocol que utiliza 2 pines (debug) + 1 pin (Trace),
*				que está conectado a la unidad ITM del procesador y permite entre
*				otras funciones, programar la memoria FLASH, acceder a diferentes
*				regiones de memoria, agregar beakpoints, etc, es decir, permite
*				hablar con el procesador.
 *            - la libreria printf de C, realiza una llamada a la función write
 *              implementada en syscalls.c
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void)
{
	printf("Hello STM World!\n");
    /* Loop forever */
	for(;;);
}
